excluded:
  - .build
  - Package.swift
  - scripts

trailing_comma:
  mandatory_comma: false

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 60
  error: 100

line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  allowed_symbols: ["_"]

file_length:
  warning: 500
  error: 600

cyclomatic_complexity:
  warning: 20
  error: 30
