name: MangaViewer
options:
  bundleIdPrefix: work.okamyuji
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: "0.9.0"
  Unrar.swift:
    url: https://github.com/mtgto/Unrar.swift.git
    from: "0.3.0"

targets:
  MangaViewer:
    type: application
    platform: macOS
    sources:
      - path: Sources/MangaViewer
      - path: Resources
    dependencies:
      - package: ZIPFoundation
      - package: Unrar.swift
        product: Unrar
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: work.okamyuji.mangaviewer
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: MangaViewer.entitlements
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_UPCOMING_FEATURE_STRICT_CONCURRENCY: true
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: false
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O

  MangaViewerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/MangaViewerTests
    dependencies:
      - target: MangaViewer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: work.okamyuji.mangaviewer.tests
        GENERATE_INFOPLIST_FILE: true
